name: paladin-android-ci

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get App version
        uses: mikefarah/yq@master
        with:
          cmd: echo "VERSION=$(yq .version pubspec.yaml)" >> $GITHUB_ENV
      - name: "Push version tag from pubspec.yaml"
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ env.VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: false
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run flutter_launcher_icons
        # Create relevant secret files for the Android build
      - name: Create relevant secret files
        run: |
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEY_BASE_64 }}
        run: |
          echo $ENCODED_STRING | base64 -d > android/app/keystore.jks
      - run: flutter build apk --release --no-tree-shake-icons
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: 'paladin-${{ env.VERSION }}.apk'
          files: 'build/app/outputs/apk/release/paladin-${{ env.VERSION }}-release.apk'
          tag_name: ${{ env.VERSION }}
