name: paladin-android-ci

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get App version
        uses: mikefarah/yq@master
        with:
          cmd: echo "VERSION=$(yq .version pubspec.yaml)" >> $GITHUB_ENV
      - name: "Push version tag from pubspec.yaml"
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ env.VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: false
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run flutter_launcher_icons
      - run: flutter build apk --release --no-tree-shake-icons
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/paladin-release.apk
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/paladin-release.apk"
          tag: v${{ env.VERSION }}
          #token: ${{ secrets.TOKEN }}